testcases:
- interfaceName: /operation-manage/featured/modifyIndexConfig
  case:
  - testPoint: 修改运营位配置
    preConditions:
    - setupGetFirstSearchResource
    - setupAddOperPosition
    - setupGetFirstConfigResource
    - setupSetAlertResource
    - setupGetFirstSearchResource
    - tearDownDelOneOperpsn
    operationSteps: compareRetcodeTest
    testData:
    - title: 让MakeX成为青少年释放自我的舞台
      alertTitle: 让MakeX成为青少年释放自我的舞台-接口自动化-勿动
      picPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425150543_430837.jpg
      alertPicPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425150543_430837.jpg
      position: '01'
      resourceTypeId: 2
      resourceType: 2
      displayType: '2'
      ids: []
      caseid: operpsn_add_1
      testPoint: 新增一个运营位配置-首页banner-文章
    expectedResult:
      code: '000000'
      compare:
        - comparePoint: 验证返回码为'000000'
          expectData: '000000'
          actualData: getRetcodeByRsp
          fun: assertEqual