testcases:
- interfaceName: /operation-manage/featured/queryShowConfigs
  case:
  - testPoint: 查询运营位配置
    preConditions:
    - ''
    operationSteps: compareRetcodeTest
    testData:
    - position: '01'
      title: 让MakeX成为青少年释放自我的舞台-接口自动化-勿动
      caseid: operpsn_query_1
      testPoint: 查询首页运营位配置存在文章内容
    expectedResult:
      code: '000000'
