testcases:
- interfaceName: /operation-manage/featured/createConfig
  case:
  - testPoint: 新增一个运营位配置-首页banner-文章
    preConditions:
    - setupGetFirstSearchResource
    - tearDownGetFirstConfigResource
    - tearDownDelOneOperpsn
    operationSteps: compareRetcodeTest
    testData:
    - title: 让MakeX成为青少年释放自我的舞台-接口自动化-勿动
      picPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425150543_430837.jpg
      listOrder: 1
      position: '01'
      resourceTypeId: 2
      displayType: '2'
      caseid: operpsn_add_1
      testPoint: 新增一个运营位配置-首页banner-文章
    expectedResult:
      code: '000000'
  - testPoint: 新增一个运营位配置-首页banner-视频
    preConditions:
    - setupGetFirstSearchResource
    - tearDownGetFirstConfigResource
    - tearDownDelOneOperpsn
    operationSteps: compareRetcodeTest
    testData:
    - title: 石舍学校独立微电影-接口自动化-勿动
      picPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425150543_430837.jpg
      listOrder: 1
      resourceTypeId: 1
      position: '01'
      displayType: '1'
      caseid: operpsn_add_2
      testPoint: 新增一个运营位配置-首页banner-视频
    expectedResult:
      code: '000000'
  - testPoint: 新增一个运营位配置-首页banner-商品
    preConditions:
    - setupGetFirstSearchResource
    - tearDownGetFirstConfigResource
    - tearDownDelOneOperpsn
    operationSteps: compareRetcodeTest
    testData:
    - title: 早教学习儿童编程机器人套件益智智能机器人-接口自动化-勿动
      picPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425150543_430837.jpg
      listOrder: 1
      resourceTypeId: 11
      position: '01'
      displayType: '1'
      caseid: operpsn_add_3
      testPoint: 新增一个运营位配置-首页banner-商品
    expectedResult:
      code: '000000'
  - testPoint: 新增一个运营位配置-首页banner-活动
    preConditions:
    - setupGetFirstSearchResource
    - tearDownGetFirstConfigResource
    - tearDownDelOneOperpsn
    operationSteps: compareRetcodeTest
    testData:
    - title: 山野少年之户外实战技巧-接口自动化-勿动
      picPath: http://uat-steam.opg.cn/_static/admin/images/resource/20180425150543_430837.jpg
      listOrder: 1
      resourceTypeId: 12
      position: '01'
      displayType: '1'
      caseid: operpsn_add_4
      testPoint: 新增一个运营位配置-首页banner-活动
    expectedResult:
      code: '000000'