testcases:
- interfaceName: /featured/index/configs/pageQueryPositionShows
  case:
  - testPoint: 用户浏览首页-热门推荐运营位配置内容
    preConditions:
    - ''
    operationSteps: compareRetcodeTest
    testData:
    - phoneNo: '18916899938'
      position: '03'
      currentPage: 1
      caseid: home_page_1
      testPoint: 用户浏览首页-热门推荐运营位配置内容
    expectedResult:
      code: '000000'
  - testPoint: 用户浏览发现页-计算推荐内容
    preConditions:
    - ''
    operationSteps: compareRetcodeTest
    testData:
    - phoneNo: '18916899938'
      position: '09'
      currentPage: 1
      caseid: find_page_cal_1
      testPoint: 用户浏览发现页-计算推荐内容
    expectedResult:
      code: '000000'
  - testPoint: 用户浏览创新大赛-计算内容列表
    preConditions:
    - ''
    operationSteps: compareRetcodeTest
    testData:
    - phoneNo: '18916899938'
      position: '04'
      currentPage: 1
      caseid: home_page_1
      testPoint: 用户浏览创新大赛-计算内容列表
    expectedResult:
      code: '000000'
