testcases:
- interfaceName: /steam-resource/index/configs/searchByEntry
  case:
  - testPoint: 按分类搜索内容
    preConditions:
    - ''
    operationSteps: compareRetcodeTest
    testData:
    - currentPage: 1
      pageSize: 10
      resourceTypeId: 11
      keyword: 早教学习儿童编程机器人套件益智智能机器人
      phoneNo: '18916899938'
      entryName: 线上课堂
      position: '05'
      pageType: 1
      entryId: 75
      caseid: user_search_entry_1
      testPoint: 按分类搜索内容
    expectedResult:
      code: '000000'
